function [sample_nr, Voltage] = importECG(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [SAMPLE_NR, VOLTAGE] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [SAMPLE_NR, VOLTAGE] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [sample_nr, Voltage] = importfile("C:\Users\julia\Downloads\Untitled_Message\opensignals_NaserSyncTest_2022-02-17_13-49-09.txt", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Feb-2022 15:12:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["sample_nr", "Var2", "Voltage"];
opts.SelectedVariableNames = ["sample_nr", "Voltage"];
opts.VariableTypes = ["double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var2", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
sample_nr = tbl.sample_nr;
Voltage = tbl.Voltage;
end